# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Powerofus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Powerofus
  pod 'SnapKit', '~> 4.0.0'
  pod 'Socket.IO-Client-Swift', '~> 12.1.2'
  pod 'Alamofire', '~> 4.5'
  pod 'Material', '~> 2.0'
  
  # UserDefaults
  pod 'SwiftyUserDefaults'

  target 'PowerofusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PowerofusUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
